zplot_str = \
    ["ZPLOT2 ASCII\n",
        "  Measured Data, ZPlot:       2.9\n",
        "  Experiment Type:            Sweep Frequency, Control Voltage\n",
        "  Date:                       11-19-2010\n",
        "  Time:                       10:44:30\n",
        "  Open Circuit Potential (V): 0\n",
        "  Begin User Comments:        0\n",
        "  End User Comments:          0\n",
        "  Begin Experiment:           0\n",
        "    Potential-DC:             5\n",
        "    Potential-DC Type:        1\n",
        "    Potential-AC:             250\n",
        "    Potential-Monitor Type:   0\n",
        "    Potential-Monitor TargetI:1\n",
        "    Potential-Monitor Limit:  3000\n",
        "    Potential-Monitor Error:  25\n",
        "    Current-DC:               0\n",
        "    Current-AC:               0.1\n",
        "    Current-Monitor Type:     0\n",
        "    Current-Monitor TargetE:  20\n",
        "    Current-Monitor Limit:    60\n",
        "    Current-Monitor Error:    25\n",
        "    vs Freq-Initial:          15000\n",
        "    vs Freq-Final:            0.01\n",
        "    vs Freq-Lin/Log Type:     1\n",
        "    vs Freq-Linear Type:      1\n",
        "    vs Freq-Linear Interval:  100\n",
        "    vs Freq-Log Type:         0\n",
        "    vs Freq-Log Interval:     10\n",
        "    Harmonics:                3\n",
        "    PolE-Initial:             0\n",
        "    PolE-Final:               0.2\n",
        "    PolE-InitialType:         1\n",
        "    PolE-FinalType:           1\n",
        "    PolE-SweepRate:           1\n",
        "    PolE-SweepRateType:       0\n",
        "    PolE-DataRate:            5\n",
        "    PolE-SegmentNo:           2\n",
        "    PolE-IR:                  0\n",
        "    AmplE-Initial:            10\n",
        "    AmplE-Final:              200\n",
        "    AmplE-SweepRate:          1\n",
        "    AmplE-DataRate:           5\n",
        "    AmplE-SegmentNo:          2\n",
        "    PolI-Initial:             0\n",
        "    PolI-Vertex:              0.01\n",
        "    PolI-Final:               0.01\n",
        "    PolI-SweepRate:           0.1\n",
        "    PolI-SweepRateType:       0\n",
        "    PolI-DataRate:            5\n",
        "    PolI-SegmentNo:           2\n",
        "    AmplI-Initial:            0.1\n",
        "    AmplI-Final:              10\n",
        "    AmplI-SweepRate:          0.1\n",
        "    AmplI-DataRate:           5\n",
        "    AmplI-SegmentNo:          2\n",
        "    vs Time-Freq:             1000\n",
        "    vs Time-Harmonic:         1\n",
        "    vs Time-Total Time:       100\n",
        "    vs Time-Time Type:        0\n",
        "    vs Time-Interval:         5\n",
        "  End Experiment:             0\n",
        "  Begin Pstat/Gstat:          -1\n",
        "    Pstat Range High:         -1\n",
        "    Pstat Range Low:          -1\n",
        "    Pstat Range Frequency:    5000\n",
        "    Pstat Range Minimum:      -1\n",
        "    Pstat Limit Range:        -1\n",
        "    Pstat Limit Type:         2\n",
        "    Pstat Bandwidth:          -1\n",
        "    Pstat Use Aux:            0\n",
        "    Gstat Range:              -1\n",
        "    Gstat Bandwidth:          -1\n",
        "    Filter:                   1\n",
        "    Error Beep:               0\n",
        "    Bias Rejection:           1\n",
        "    Attenuator:               2\n",
        "    Grounding:                0\n",
        "    Manual Normalize:         5\n",
        "    Manual Cell Warning:      1\n",
        "    Manual Sign Convention:   0\n",
        "    Manual Attenuator:        0\n",
        "    Manual Range:             0\n",
        "    Calibration File\n",
        "    Nulling-Short File\n",
        "    Nulling-Open File\n",
        "  End Pstat/Gstat:            -1\n",
        "  Begin Analyzer:             1260\n",
        "    Z60 Mode:                 3\n",
        "    Z60 GD Freq-:             5\n",
        "    Z60 GD Freq+:             5\n",
        "    Bias Voltage:             0\n",
        "    Auto Integration Type:    0\n",
        "    Integration Time Type:    0\n",
        "    Integration Seconds:      0.2\n",
        "    Integration Cycles:       1\n",
        "    Delay Time Type:          1\n",
        "    Delay Seconds:            0\n",
        "    Delay Cycles:             0\n",
        "    Source:                   2\n",
        "    SourceI:                  1\n",
        "    Error Beep:               0\n",
        "    Range V1:                 0\n",
        "    Coupling V1:              1\n",
        "    Input V1:                 1\n",
        "    Outer V1:                 1\n",
        "    Location V1:              0\n",
        "    Range V2:                 0\n",
        "    Coupling V2:              1\n",
        "    Input V2:                 1\n",
        "    Outer V2:                 1\n",
        "    Location V2:              0\n",
        "    Coupling I:               0\n",
        "  End Analyzer:               1260\n",
        "  Begin Information:          Cell Information\n",
        "    Surface Area:             25\n",
        "    Density:                  0\n",
        "    Weight:                   0\n",
        "    Polarity:                 0\n",
        "    PolarityI:                0\n",
        "    Corrosion Unit Type:      0\n",
        "    Reference Type:           0\n",
        "    Reference Potential:      0\n",
        "    User-Defined Potential:   0\n",
        "    Stern-Geary:              26\n",
        "  End Information:            Cell Information\n",
        "  Null Configuration:         0,3,0,1,15000,0.01\n",
        "  Data Points:                57\n",
        "  Freq(Hz)	Ampl	Bias	Time(Sec)	Z'(a)	Z''(b)	GD	Err	Range\n",
        "End Comments\n"]
